//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: TestClass.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TestClass")
#ifdef RESTRICT_TestClass
#define INCLUDE_ALL_TestClass 0
#else
#define INCLUDE_ALL_TestClass 1
#endif
#undef RESTRICT_TestClass

#if !defined (TestClass_) && (INCLUDE_ALL_TestClass || defined(INCLUDE_TestClass))
#define TestClass_

@interface TestClass : NSObject

#pragma mark Public

- (void)testFunc;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(TestClass)

FOUNDATION_EXPORT void TestClass_init(TestClass *self);

FOUNDATION_EXPORT TestClass *new_TestClass_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT TestClass *create_TestClass_init(void);

J2OBJC_TYPE_LITERAL_HEADER(TestClass)

#endif

#pragma pop_macro("INCLUDE_ALL_TestClass")
